### ISSUE TITLE
Preferences Page

### ISSUE THREAD

**Issue by mfinotti** [kairostech-sw/kairoshub-configuration#11]
# Preferences Page (Step 1/3)
La pagina delle Preferenze da la possibilità all'utente di poter personalizzare il comportamento dei sensori e delle automazione attraverso il settaggio di parametri. Il settaggio dei parametri non è obbligatorio e viene proposto sempre un valore di default di riferimento. 

**Task list**

- [x] Pagina Preferenze
- [x] [Preference entities](https://github.com/kairostech-sw/kairoshub/issues/8)
- [x] Preferenze Tapparelle
- [x] [Automations](https://github.com/kairostech-sw/kairoshub/issues/9)
- [x] [Follow Preferences persistence](https://github.com/kairostech-sw/kairoshub/issues/10)

## Pagina Preferenze
Aggiungere la nuova pagina **PREFERENZE** con layout simile a quella del clima. Il layout della pagina si presenta nel seguente modo: 

> Titolo
> Predisposizione per 8 Button giganti cliccabili. Il button riporta l'icona in grande del gruppo di preferenze e il titolo. Tappando sul button si va alla pagina specifica di preferenza. 

Aggiungere la pagina al routing dell'applicazione `lovelace-kairoshome.yaml`, impostandolo come visibile nella navbar, in ordine prima della pagina ASSISTENZA. 

> title: PREFERENZE
>     path: preferenze
>     panel: true
>     cards:
>       - type: vertical-stack
>         cards:
>           - !include hakairos-configuration/frontend/panels/preferences.yaml

## Preferenze Tapparelle
E' il primo dei button tappabili, cliccando l'applicazione si sposta nella pagina dedicata attraverso l'url `/prefenze/tapparelle`. La pagina di personalizzazione eredita il layout della pagina preferenze, con la possibilità di tornare alla pagina precedente attraverso il button `Indietro`. 
Le personalizzazioni al momento disponibili sono: 

_Posizione tapparelle stato: In casa_
> tipologia: slider?
> valori: 0-100
> step: 5
> default: 100

_Posizione tapparelle stato: Fuori casa_
> tipologia: slider?
> valori: 0-100
> step: 5
> default: 0

Aggiungere la pagina al routing dell'applicazione. 
> title: PREFERENZE TAPPARELLE
>     path: preferenze-tapparelle
>     panel: true
> visible: false
>     cards:
>       - type: vertical-stack
>         cards:
>           - !include hakairos-configuration/frontend/panels/preferences/tapparelle.yaml
