### ISSUE TITLE
Statistics push

### ISSUE THREAD

**Issue by mfinotti** [kairostech-sw/kairoshub-configuration#6]
# Statistics push 2/2
Predisporre una nuova applicazione appdaemon che si occuperà di impacchettare le statistiche e di inviarle sull'apposito TOPIC Kafka `HASSIO_SYSTEM_METRICS`.  [Passo 1 del task](https://github.com/kairostech-sw/kairoshub/issues/7)

**Task da completare**
- [x] Nuova applicazione appdaemon
- [x] Get valori dai sensori
- [x] Impacchettare il messaggio
- [x] Dispatch evento

## Nuova applicazione appdaemon
Aggiungere una nuova applicazione appdaemon chiamata `systemMetrics`. Oltre a creare la classe sulla falsa riga della classe `HelloWorld` è necessario aggiungerla al bootstrap di appdaemon, ovvero, nel file `apps.yaml`

## Get valori dai sensori
Recuperare lo stato dei sensori statistici creati nella issue collegata, ovvero: 
- `disk_use_percent`
- `memory_use_percent`
- `processor_use`
- `processor_temperature`
- `last_boot`
 
## Impacchettare il messaggio
Impacchettare il messaggio da inviare come di seguito: 

> statMessage["disk_use"] = _valore disk_use_percent_
> statMessage["memory_use"] = _valore memory_use_percent_
> statMessage["processor_use"] = _valore processor_use_
> statMessage["processor_temperature"] = _valore processor_temperature_
> statMessage["last_boot"] = _valore last_boot_
> **statMessage["processor_max_use"] = _valore processor_use, attributo max_value_**

_**UPDATE 01/09/2022**_
Aggiungere al pacchetto l'informazione sul massimo utilizzo della CPU. Questa informazione è disponibile come attributo della entity dedicata al processo_use. 
![image](https://user-images.githubusercontent.com/1792518/187890755-3fa2ce09-3fdf-46a4-8927-266c57452fa9.png)

## Dispatch evento
Una volta impacchettato il messaggio aggiungere le informazioni aggiuntive necessarie a avere un messaggio sintatticamente corretto.

> eventData = {
>             "eventType" : "TECHNICAL",
>             "systemCode": systemCode, 
>             "platform"  : "HASSIO_EVENT",
>             "message"   : "STATISTICS PUSH",
>             "technicalMessage": statMessage
> }

`systemCode:  _valore input_text.system_code_`

In fine, si può dispatchare l'evento per permettere al proder kafka di inviare le metriche calcolate al cloud. 
`self.fire_event("HAKAFKA_PRODUCER_PRODUCE", topic="HASSIO_SYSTEM_METRICS", message=eventData)`

**Comment by mfinotti** [comment]
** UPDATE 28/09/2022 ** 
Diversamente da come descritto nella sezione Dispatch evento, il messaggio viene impacchettato nel seguente modo: 

> eventData = {
>             "eventType" : "STATISTICS_PUSH",
>             "systemCode": {systemCode},
>             "message" : "STATISTICS PUSH",
>             "technicalMessage": statMessage
>         }

E viene dispatchato l'evento come di seguito: 
`self.fire_event("HAKAFKA_PRODUCER_PRODUCE", topic="TECHNICAL", message=eventData)`
